from django.core.mail import send_mail  # For sending emails
from django.conf import settings
from rest_framework.response import Response
from rest_framework import status


# function that contain the general view of an email sent by racing team
# params:
# sender : string of sender email
# receiverList : list of strings containing all receiving Emails
# subject : Email subject
# content : details of an Email

def sendRTMail(sender=settings.EMAIL_HOST_USER, receiverList=['a.ebeid@hotmail.com'],subject="testing email functionality", header="ASU RacingTeam",content="Reason Of Email",footer='Thank You'):
    try:
        message0='​<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>@font-face{font-family:"RT";font-style:normal;font-weight:400;src:local("Lato Regular"), local("Lato-Regular"), url(https://drive.google.com/open?id=0B-DDVBOzmqwBQmdTeFQzNXRuN3M) format("woff")}a{color:#6c757d}#facebook:hover{color:#3b5998}#instagram:hover{color:#417399}#youtube:hover{color:#F00}#twitter:hover{color:#00aced}#linkedin:hover{color:#0077B5}.Copyrights{color:white;font-size:11px}p{color:white}.container{width:100%;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}@media (min-width: 576px){.container{max-width:540px}}@media (min-width: 768px){.container{max-width:720px}}@media (min-width: 992px){.container{max-width:960px}}@media (min-width: 1200px){.container{max-width:1140px}}.container-fluid{width:100%;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}.row{display:-webkit-box;display:-ms-flexbox;display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;margin-right:-15px;margin-left:-15px}.med{display:block;background-color:rgb(250, 246, 246);padding:15px 0px;width:100%;border-radius:15px;margin:auto}.justify-content-center{-webkit-box-pack:center !important;-ms-flex-pack:center !important;justify-content:center !important}.col,.col-2,.col-3,.col-12,.col-sm-12,.col-md-12,.col-lg-4,.col-lg-12,.col-xl-12{position:relative;width:100%;min-height:1px;padding-right:15px;padding-left:15px}.container-fluid{width:100%;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto}.mt-auto,.my-auto{margin-top:auto !important}.text-center{text-align:center !important}@media (min-width: 576px){.text-sm-left{text-align:left !important}.text-sm-right{text-align:right !important}.text-sm-center{text-align:center !important}}.text-muted{color:#6c757d !important}.col{-ms-flex-preferred-size:0;flex-basis:0;-webkit-box-flex:1;-ms-flex-positive:1;flex-grow:1;max-width:100%}.col-2{-webkit-box-flex:0;-ms-flex:0 0 16.666667%;flex:0 0 16.666667%;max-width:16.666667%}.col-3{-webkit-box-flex:0;-ms-flex:0 0 25%;flex:0 0 25%;max-width:25%}.col-12{-webkit-box-flex:0;-ms-flex:0 0 100%;flex:0 0 100%;max-width:100%}@media (min-width: 576px){.col-sm-12{-webkit-box-flex:0;-ms-flex:0 0 100%;flex:0 0 100%;max-width:100%}}@media (min-width: 768px){.col-md-12{-webkit-box-flex:0;-ms-flex:0 0 100%;flex:0 0 100%;max-width:100%}}@media (min-width: 992px){.col-lg-4{-webkit-box-flex:0;-ms-flex:0 0 33.333333%;flex:0 0 33.333333%;max-width:33.333333%}.col-lg-12{-webkit-box-flex:0;-ms-flex:0 0 100%;flex:0 0 100%;max-width:100%}}@media (min-width: 1200px){.col-xl-12{-webkit-box-flex:0;-ms-flex:0 0 100%;flex:0 0 100%;max-width:100%}}.header{font-weight:bold;color:#E60000;font-family:RT}.footer{font-size:13px;color:#E60000;font-family:RT}.content{font-family:RT;}</style></head>'
        message1='​<body><div style="margin-top: -8px;margin-left: -8px;"><div class="container" style="width:80%;padding:40px;background-color:black;"><div><div style="text-align:center" class="align-self-center"> <img src="http://asuracingteam.org/assets/navbar/logo.png" width="230px" class="img-fluid" alt="RT logo"></div></div> <br> <br><div class="row"><div class="col"><div class="med"><div class="row header"><pre style="font-size: 16px;white-space: pre-line;padding: 3px 32px;"> '+header+'</pre></div><div class="row content"><pre style="font-size: 16px;white-space: pre-line;padding: 3px 32px;"> '+content+' </pre></div><div class="row footer"><pre style="font-size: 16px;white-space: pre-line;padding: 3px 32px;"> '+footer+'</pre></div></div></div></div> <br> <br><div class="footer" style="background-color:black;"><div class="container-fluid" style="padding: 0px;"><div class="row"><div class="col-12 my-auto text-center" style="margin: auto;padding-top: 1%;padding-bottom: 1%;padding-right: 0px;padding-left: 0px;"><div style="padding:0px;" class="my-auto text-center text-muted Copyrights">Copyright 2019 ASU RACING TEAM <br>All Rights Reserved.</div></div></div>'
        message2='​<div class="row"><div class="row col-12 my-auto text-center justify-content-center" style="width: fit-content;margin: auto;padding: 1% 0px;"> <a style="padding: 0px 5px;text-decoration:none;" href="https://www.facebook.com/ASU.Racing.Team/" title="Facebook" target="_blank"> <img src="https://imgur.com/Y3QRjPi.png" alt="Facebook" title="Facebook" width="32"> </a> <a style="padding: 0px 5px;text-decoration:none;" href="https://twitter.com/asuracingteam" title="Twitter" target="_blank"> <img src="https://imgur.com/ksqVvNO.png" alt="Twitter" title="Twitter" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a> <a style="padding: 0px 5px;text-decoration:none;" href="https://www.linkedin.com/company/10910709/" title="LinkedIn" target="_blank"> <img src="https://imgur.com/ZUYgczz.png" alt="LinkedIn" title="LinkedIn" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a>'
        message3='​ <a style="padding: 0px 5px;text-decoration:none;" href="https://www.instagram.com/asu.rt/" title="Instagram" target="_blank"> <img src="https://imgur.com/XS5FgPs.png" alt="Instagram" title="Instagram" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a> <a style="padding: 0px 5px;text-decoration:none;" href="https://www.youtube.com/user/asuracingteam/" title="YouTube" target="_blank"> <img src="https://imgur.com/qhcII1a.png" alt="YouTube" title="YouTube" width="32" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: none;height: auto;float: none;max-width: 32px !important"> </a></div></div></div></div></div></div></body></html>'
        message = message0 + message1 + message2 + message3 
        
        send_mail(subject, message="nothing", from_email=sender, recipient_list=receiverList, fail_silently=False,html_message=message)
        return Response({"Success": "Email Sent Successfully","data":'sender: '+sender+' ,reciever: '+receiverList[0]}, status=status.HTTP_200_OK)
    except Exception as e:
        # print('%s (%s)' % (e.message, type(e)))
        return Response({"error": "Email Issue ","errors":e}, status=status.HTTP_503_SERVICE_UNAVAILABLE)

