# Generated by Django 2.1.7 on 2019-03-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('profile_pic', models.FileField(upload_to='pics')),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('college_department', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('college_id', models.CharField(default='', max_length=15, unique=True)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_mobile', models.CharField(max_length=15)),
                ('emergency_relation', models.CharField(max_length=50)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('national_front', models.FileField(upload_to='pics')),
                ('national_back', models.FileField(upload_to='pics')),
                ('passport_id', models.CharField(blank=True, default='', max_length=9, unique=True)),
                ('passport_img', models.FileField(upload_to='pics')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
